### PR TITLE
Registeration

### PR DESCRIPTION
**Pull request by annielin28815**
**1.add facebook_api**

- gem 'omniauth-facebook'
- gem 'figaro' 

**2.ngrok set_up**

**3.add google_api**

- gem 'omniauth-google'

### CODE REVIEW

**Review by kihifung — APPROVED** [review]
ok

**Review by xx4673 — APPROVED** [review]
checked

**Comment by xx4673** [comment]
checked

**Comment by xx4673** [comment]
checked

**Comment by xx4673** [comment]
checked

**Review by samliuforwork — APPROVED** [review]
ok

**Pull request merged**
